name: Automatic Deploy

on:
  push:
    branches: [master]

jobs:
  deployOnServer:
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - name: Configure SSH
        run: |        
          eval $(ssh-agent -s)

          echo "$SSH_KEY" | tr -d '\r' | ssh-add -

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Kill Running Process
        run: ssh $SSH_USER@$SSH_HOST 'pkill -f rush.py'
      - name: Deploy
        run: ssh $SSH_USER@$SSH_HOST 'cd github/rush; tmux send-keys -t rush "git pull && python ~/github/rush/telegram/rush.py" ENTER'
