name: Build And Test

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: self-hosted

    env:
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
      ESP8266_ADDRESS_PORT: ${{ secrets.ESP8266_ADDRESS_PORT }}
      SYSTEM_1_ADDRESS: ${{ secrets.SYSTEM_1_ADDRESS }}
      SYSTEM_2_ADDRESS: ${{ secrets.SYSTEM_2_ADDRESS }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: cd ./src/main && go build -v

      - name: deploy
        run: chmod +x .github/workflows/deployScript.sh && 
          ./.github/workflows/deployScript.sh 
            $TELEGRAM_API_KEY $ESP8266_ADDRESS_PORT 
              $SYSTEM_1_ADDRESS $SYSTEM_2_ADDRESS
