name: Build And Test

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: self-hosted

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Fetch required Go modules
      #   run:  go mod download

      - name: Build
        run: cd ./src/main && go build -v

      - name: deploy
        run: tmux send-keys -t ambrosioBot "^C" Enter &&
          cd ./src/main && 
          mv main /home/luis/github/ambrosioBot && 
          cd /home/luis/github/ambrosioBot &&
          tmux send-keys -t ambrosioBot "TELEGRAM_API_KEY=${{ secrets.TELEGRAM_API_KEY }} ./main" Enter
