name: Build And Test

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: self-hosted

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
      ESP8266_ADDRESS_PORT: ${{ secrets.ESP8266_ADDRESS_PORT }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: cd ./src/main && go build -v

      - name: deploy
        run: if tmux list-windows | grep -q 'ambrosioBot'; 
                then echo "Window exists"
              else 
                echo "Window does not exist" 
                tmux new-session -s ambrosioBot
              fi &&
          tmux send-keys -t ambrosioBot "^C" Enter &&
          cd ./src/main &&
          mv main /home/lrm/sideProjs/ambrosioBot &&
          tmux send-keys -t ambrosioBot "cd /home/lrm/sideProjs/ambrosioBot" Enter && 
            tmux send-keys -t ambrosioBot "TELEGRAM_API_KEY=${{ secrets.TELEGRAM_API_KEY }} ESP8266_ADDRESS_PORT=${{ secrets.ESP8266_ADDRESS_PORT }} ./main" Enter
