name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-docker:
    runs-on: self-hosted

    env:
      TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
      ESP8266_ADDRESS_PORT: ${{ secrets.ESP8266_ADDRESS_PORT }}
      SYRINX_VARS: ${{ secrets.SYRINX_VARS }}
      SNOWDOG_VARS: ${{ secrets.SNOWDOG_VARS }}
      THINKPADX1_VARS: ${{ secrets.THINKPADX1_VARS }}

    defaults:
      run:
        working-directory: ./

    name: Run Deploy Script
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Deploy Script
        run: chmod +x .github/workflows/deployScript.sh &&
          ./.github/workflows/deployScript.sh $TELOXIDE_TOKEN $ESP8266_ADDRESS_PORT $SYRINX_VARS $SNOWDOG_VARS $THINKPADX1_VARS
